{
 "title": "Pizza Dashboard",
 "time": { "from": "2026-03-16T18:44:38.169Z", "to": "2026-03-17T00:44:38.169Z" },
 "panels": [
  {
   "title": "JWT Pizza Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{source=\"jwt-pizza-service-test\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pizza_latency_milliseconds{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "Pizza Latency (ms)"
    }
   ]
  },
  {
   "title": "Auth Sucesses and Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "auth_success_total{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "Auth Success"
    },
    {
     "expr": "auth_failure_total{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "Auth Failure"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "request_latency_milliseconds{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "Latency (ms)"
    }
   ]
  },
  {
   "title": "CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Pizza Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pizzas_sold_total{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "Pizzas sold"
    },
    {
     "expr": "pizza_failures_total{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "Pizza failures"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 24 },
   "targets": [
    {
     "expr": "revenue_usd_total{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Endpoint Requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "http_requests_total{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "HTTP Requests"
    },
    {
     "expr": "http_get_total{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "HTTP GET"
    },
    {
     "expr": "http_post_total{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "HTTP POST"
    },
    {
     "expr": "http_put_total{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "HTTP PUT"
    },
    {
     "expr": "http_delete_total{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "HTTP DELETE"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 33 },
   "targets": [
    {
     "expr": "active_users_ratio{source=\"jwt-pizza-service-test\"}",
     "legendFormat": "Active Users"
    }
   ]
  }
 ]
}